[package]
name = "wiringPi-bindings"
version = "0.1.0"
authors = ["Dylan Maccora <maccora17@gmail.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.23"

# This is the idea to only produce those that are desired but bindgen is proving
# to be difficult
[features]
serial = []
